"""SD-01 verifier: real-artifact integration test (the SD-01 verifier reads
fixed, well-known paths under lab_root -- the real committed SD-01
artifacts from configs/sharpe_decay_sd_v1/ and evidence/sharpe_decay_sd_v1/
init_archive/ ARE the fixture here, matching this lab's own precedent of
testing a phase's verifier against its own real, already-built evidence
once that evidence exists)."""
from __future__ import annotations

from crypto_regime_lab.sd.verifier_sd01 import INIT_ORIGINS, REQUIRED_GATES, verify_sd01


def test_required_gates_shape():
    assert set(REQUIRED_GATES) == {"G1-SOURCE", "G1-SHARPE", "G1-WIRING", "G1-TIMELINE",
                                   "G1-ARCHIVE", "G1-RESOURCE", "G1-REPORT"}


def test_init_origins_matches_the_frozen_timeline_count():
    assert len(INIT_ORIGINS) == 12


def test_g1_source_passes_on_the_real_committed_registration_and_migration(lab_root):
    verdict = verify_sd01(lab_root=lab_root)
    assert verdict["gates"]["G1-SOURCE"]["pass"], verdict["gates"]["G1-SOURCE"]["reasons"]


def test_g1_timeline_passes_on_the_real_frozen_timeline(lab_root):
    verdict = verify_sd01(lab_root=lab_root)
    assert verdict["gates"]["G1-TIMELINE"]["pass"], verdict["gates"]["G1-TIMELINE"]["reasons"]


def test_g1_archive_passes_on_the_real_12_origin_build(lab_root):
    """The real archive this session built: 12/12 origins, 192 label rows,
    192/192 IS+FWD OK, 12/12 anchor Y=0 -- re-derived from the raw ledger
    files by the verifier itself, not read from a summary."""
    verdict = verify_sd01(lab_root=lab_root)
    assert verdict["gates"]["G1-ARCHIVE"]["pass"], verdict["gates"]["G1-ARCHIVE"]["reasons"]
    summary = verdict["archive_summary"]
    assert summary["n_origins"] == 12
    assert summary["total_label_rows"] == 192
    assert summary["is_ok"] == 192
    assert summary["fwd_ok"] == 192
    assert summary["anchor_zero_ok"] == 12


def test_g1_resource_passes_on_the_real_micro_profile(lab_root):
    verdict = verify_sd01(lab_root=lab_root)
    assert verdict["gates"]["G1-RESOURCE"]["pass"], verdict["gates"]["G1-RESOURCE"]["reasons"]


def test_g1_report_fails_before_report_md_exists_or_passes_after(lab_root):
    """Whichever state report.md is currently in (not yet generated, or
    already generated by scripts/run_sd01_report.py), this gate's own
    verdict must be internally consistent with that file's real presence."""
    from pathlib import Path

    report_path = Path(lab_root) / "evidence" / "sharpe_decay_sd_v1" / "init_archive" / "report.md"
    verdict = verify_sd01(lab_root=lab_root, report_path=report_path if report_path.is_file() else None)
    gate = verdict["gates"]["G1-REPORT"]
    if not report_path.is_file():
        assert gate["pass"] is False
        assert any("missing" in r for r in gate["reasons"])
