"""L05.7 — synthetic worlds and negative controls.

Three worlds, because a state model can fail in three different ways and a single
fixture would only catch one:

* **no-regime** — one distribution throughout. A model that reports persistent
  states here is manufacturing structure, and that is the negative control the
  guide asks for.
* **recurring-state** — states that come back. Tests whether the model can
  re-identify a state it has seen before rather than inventing a new one.
* **structural-break** — the world changes once and does not change back. Tests
  detection delay, and tests that the model does not keep re-fitting to chase it.

The latent label generated here is GROUND TRUTH and is used only to score
diagnostics. Guide L05.7: it never enters a policy input, and no model in this lab
is allowed to see it.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

GROUND_TRUTH_IS_DIAGNOSTIC_ONLY = (
    "the latent label is generated by the simulator. It scores detection quality and never enters "
    "a feature, a model fit, or a policy input (guide L05.7)"
)


@dataclass
class World:
    name: str
    z: np.ndarray
    latent: np.ndarray
    description: str
    n_states_true: int
    ground_truth_is_diagnostic_only: str = GROUND_TRUTH_IS_DIAGNOSTIC_ONLY

    def as_record(self) -> dict:
        return {
            "name": self.name, "observations": int(self.z.shape[0]),
            "features": int(self.z.shape[1]), "n_states_true": self.n_states_true,
            "description": self.description,
            "latent_switches": int(np.count_nonzero(self.latent[1:] != self.latent[:-1])),
            "ground_truth_is_diagnostic_only": self.ground_truth_is_diagnostic_only,
        }


def no_regime_world(n: int = 600, n_features: int = 4, *, seed: int = 11,
                    noise: float = 1.0) -> World:
    rng = np.random.default_rng(seed)
    z = rng.normal(0.0, noise, size=(n, n_features))
    return World("no_regime", z, np.zeros(n, dtype=np.int64),
                 "one distribution throughout; any persistent state structure reported here is "
                 "manufactured", 1)


def recurring_state_world(n: int = 900, n_features: int = 4, *, seed: int = 12,
                          n_states: int = 3, dwell: int = 60, separation: float = 2.0,
                          noise: float = 1.0) -> World:
    rng = np.random.default_rng(seed)
    centres = np.zeros((n_states, n_features))
    for k in range(n_states):
        centres[k, k % n_features] = separation * (1 if k % 2 == 0 else -1) * (1 + k // n_features)
    latent = np.zeros(n, dtype=np.int64)
    state, remaining = 0, dwell
    for t in range(n):
        if remaining == 0:
            state = (state + 1) % n_states          # states RECUR, in order
            remaining = dwell
        latent[t] = state
        remaining -= 1
    z = centres[latent] + rng.normal(0.0, noise, size=(n, n_features))
    return World("recurring_state", z, latent,
                 f"{n_states} states cycling with a dwell of {dwell}; tests whether a returning "
                 "state is re-identified rather than invented", n_states)


def structural_break_world(n: int = 800, n_features: int = 4, *, seed: int = 13,
                           break_at: float = 0.5, shift: float = 3.0,
                           noise: float = 1.0) -> World:
    rng = np.random.default_rng(seed)
    cut = int(n * break_at)
    latent = np.zeros(n, dtype=np.int64)
    latent[cut:] = 1
    z = rng.normal(0.0, noise, size=(n, n_features))
    z[cut:, 0] += shift
    return World("structural_break", z, latent,
                 f"a one-way shift of {shift} sigma at observation {cut}; tests detection delay, "
                 "not reversion", 2)


def detection_delay(emitted: np.ndarray, latent: np.ndarray) -> dict:
    """How many observations after a true switch before the emitted state settles.

    Reported as a distribution, not a mean: a provider that is usually instant and
    occasionally 40 bars late is a different animal from one that is always 4 late,
    and the mean hides which one you have.
    """
    emitted = np.asarray(emitted, dtype=np.int64)
    latent = np.asarray(latent, dtype=np.int64)
    switches = np.flatnonzero(latent[1:] != latent[:-1]) + 1
    delays, undetected = [], 0
    for index in switches:
        before_label = emitted[index - 1]
        found = None
        for t in range(index, min(len(emitted), index + 200)):
            if emitted[t] != before_label:
                found = t - index
                break
        if found is None:
            undetected += 1
        else:
            delays.append(found)
    return {
        "true_switches": int(switches.size),
        "detected": len(delays), "undetected": undetected,
        "delay_median": float(np.median(delays)) if delays else None,
        "delay_p90": float(np.quantile(delays, 0.9)) if delays else None,
        "delay_max": int(max(delays)) if delays else None,
        "delays": [int(d) for d in delays],
        "measure": ("observations between a true latent switch and the first emitted state change "
                    "after it; a change to ANY other state counts as detection, because the "
                    "provider is not being asked to guess the simulator's integer labels"),
    }


def label_agreement(emitted: np.ndarray, latent: np.ndarray) -> dict:
    """Best-permutation agreement, reported as a DIAGNOSTIC.

    High agreement on a synthetic world says the fit works. It says nothing about
    whether states carry economic value, and guide L05 forbids claiming otherwise.
    """
    import itertools

    emitted = np.asarray(emitted, dtype=np.int64)
    latent = np.asarray(latent, dtype=np.int64)
    labels = sorted(set(emitted.tolist()))
    truths = sorted(set(latent.tolist()))
    best = 0.0
    if labels and truths and len(labels) <= 6:
        for perm in itertools.permutations(truths, min(len(labels), len(truths))):
            lookup = {label: perm[i] for i, label in enumerate(labels[:len(perm)])}
            mapped = np.asarray([lookup.get(int(s), -1) for s in emitted])
            best = max(best, float(np.mean(mapped == latent)))
    return {
        "best_permutation_agreement": best,
        "emitted_states_used": labels, "true_states": truths,
        "diagnostic_only": True,
        "note": ("agreement with a simulator's latent label is a technical check. It is not "
                 "evidence of predictive or financial value (guide L05 exit)"),
    }
