"""Strategy-boundary contracts for event-driven execution."""

from .commands import CommandBatchView, CommandWriter
from .context import MaterializedStrategyContext, StaleStrategyContextError, StrategyContextView
from .driver import PreparedStrategyAdapter
from .requirements import (
    CallbackSchedule,
    StrategyContextRequirements,
    resolve_strategy_requirements,
    strategy_requirements,
)
from .reactive_protocols import (
    BlockIntentProviderV1,
    BlockPlanV1,
    CandidateErrorCodeV1,
    CandidateWakePlansV1,
    EquityThresholdV1,
    MarginMetricV1,
    MarginThresholdV1,
    PositionThresholdV1,
    PriceCrossConditionV1,
    ReactiveCandidateBatchStrategyV1,
    ReactiveShadowCertificationV1,
    ReactiveSparseStrategyV1,
    ThresholdDirectionV1,
    WakePlanV1,
    WakeReasonV1,
    certify_reactive_shadow_v1,
    wake_reason_names,
)
from .reactive_wfo import (
    PreparedReactiveWfoStrategyAdapterV1,
    PreparedReactiveWfoStrategyV1,
    PreparedReactiveWfoUnsupported,
    REACTIVE_WFO_SCHEMA_V1,
    ReactiveWfoPreparationV1,
    ReactiveWfoTaskV1,
    STRICT_CAUSAL_CACHE_CONTRACT_V1,
    prepare_reactive_wfo_strategy,
    reactive_wfo_candidate_id,
)
from .native_ir import (
    NativeIRLimits,
    NativeIRReferenceTape,
    NativeStrategyIR,
    NativeStrategyKind,
    NativeStrategyParameters,
    STRATEGY_IR_PARAMETER_NAMES,
    STRATEGY_IR_VERSION,
)

__all__ = [
    "CallbackSchedule",
    "BlockIntentProviderV1",
    "BlockPlanV1",
    "CandidateErrorCodeV1",
    "CandidateWakePlansV1",
    "CommandBatchView",
    "CommandWriter",
    "MaterializedStrategyContext",
    "EquityThresholdV1",
    "MarginMetricV1",
    "MarginThresholdV1",
    "PreparedStrategyAdapter",
    "PositionThresholdV1",
    "PriceCrossConditionV1",
    "ReactiveCandidateBatchStrategyV1",
    "ReactiveShadowCertificationV1",
    "ReactiveSparseStrategyV1",
    "PreparedReactiveWfoStrategyAdapterV1",
    "PreparedReactiveWfoStrategyV1",
    "PreparedReactiveWfoUnsupported",
    "REACTIVE_WFO_SCHEMA_V1",
    "ReactiveWfoPreparationV1",
    "ReactiveWfoTaskV1",
    "STRICT_CAUSAL_CACHE_CONTRACT_V1",
    "StaleStrategyContextError",
    "StrategyContextRequirements",
    "StrategyContextView",
    "ThresholdDirectionV1",
    "NativeIRLimits",
    "NativeIRReferenceTape",
    "NativeStrategyIR",
    "NativeStrategyKind",
    "NativeStrategyParameters",
    "STRATEGY_IR_PARAMETER_NAMES",
    "STRATEGY_IR_VERSION",
    "resolve_strategy_requirements",
    "strategy_requirements",
    "WakePlanV1",
    "WakeReasonV1",
    "certify_reactive_shadow_v1",
    "wake_reason_names",
    "prepare_reactive_wfo_strategy",
    "reactive_wfo_candidate_id",
]
