#!/usr/bin/env python
"""Run the whole of LAB-01 in dependency order and report the exit gate.

Reproduction entry point: everything LAB-01 claims can be regenerated by this
one command. A failing step stops the phase; no step is skipped silently.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

LAB_ROOT = Path(__file__).resolve().parent.parent
PYTHON = LAB_ROOT / "environments" / "lab_venv" / "bin" / "python"

STEPS = [
    ("L01.2  ingest original archive", ["scripts/ingest_archive.py"]),
    ("L01.2  unpack alphas in place", ["scripts/unpack_alphas_inplace.py"]),
    ("L01.1-6 bootstrap + api map", ["scripts/bootstrap_lab.py"]),
    ("L01.3  wheels + candidate copy", ["scripts/materialize_candidate.py"]),
    ("L01.3  dependency lock + separation", ["scripts/pin_environment.py"]),
    ("L01.5  preregistration + freeze policy", ["scripts/preregister_study.py"]),
    ("L01.5  preset quarantine", ["scripts/quarantine_presets.py"]),
    ("L01.2/4 boundaries + read-lock policy", ["scripts/record_boundaries.py"]),
    ("L01.6  incumbent regime probe", ["scripts/probe_incumbent_regime.py"]),
    ("gate   preflight T01-T08 + ISO", ["scripts/preflight.py"]),
]


def main() -> int:
    failures: list[str] = []
    for title, argv in STEPS:
        print(f"\n=== {title} ===")
        completed = subprocess.run([str(PYTHON), *argv], cwd=LAB_ROOT,
                                   capture_output=True, text=True, timeout=900)
        tail = [ln for ln in completed.stdout.strip().splitlines() if ln][-3:]
        for line in tail:
            print(f"    {line}")
        if completed.returncode != 0:
            failures.append(title)
            print(f"    FAILED rc={completed.returncode}")
            print(f"    {completed.stderr.strip()[-500:]}")
            break

    print("\n=== acceptance tests ===")
    tests = subprocess.run([str(PYTHON), "-m", "pytest", "tests", "-q"],
                           cwd=LAB_ROOT, capture_output=True, text=True, timeout=900)
    summary = [ln for ln in tests.stdout.strip().splitlines() if "passed" in ln or "failed" in ln]
    print(f"    {summary[-1] if summary else 'no pytest summary'}")
    if tests.returncode != 0:
        failures.append("acceptance tests")

    print("\n=== LAB-01 exit ===")
    if failures:
        print(f"    STATUS = FAILED ({', '.join(failures)})")
        return 1
    print("    STATUS = PASS")
    print("    SAFE_TO_RUN_SYNTHETIC = true")
    print("    market execution = disabled until LAB-02 certification AND LAB-03 data qualification")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
